config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'

  resources :jobs

  get 'hello/world'

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates_presence_of :description, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :all_jobs, only: [:index, :create, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  respond_to :html


  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    respond_to do |format|
      format.js { render :partial => "edit" }
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        flash[:success] = "Job was successfully created!"
        format.html { redirect_to jobs_url}
        format.json { render :show, status: :created, location: @job }
      else
        flash[:error] = "Could not create Job!"
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      format.html { redirect_to jobs_url}
      if @job.update(job_params)
        flash[:success] = "Job was successfully updated!"
        # format.json { render :show, status: :ok, location: @job }

      else
        flash[:error] = "An error occurred whil updating Job!"
        # format.json { render json: @job.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      #  flash[:success] = "Job was successfully destroyed!"
      format.js  {notice :"Job was successfully updated!"}
      # format.html { redirect_to jobs_url}
      # format.json { head :no_content }
    end
  end

  private
    def all_jobs
      @jobs = Job.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
      Rails.logger.debug("Job for update is: #{@job.title}")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/hello/world.html.erb
<h1>Hello World!</h1>

app/views/jobs/_edit.html.erb
<div class="modal-header">
  <h3 id="myModalLabel"><%= "Editing #{@job.title}" %></h3>
</div>
<%= render "form" %>

app/views/jobs/_form.html.erb
<%= form_for @job, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :title, class:"control-label" %>
      <div class="controls">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :description %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary submit" %>
    <%= link_to "Cancel", "#", class: "btn btn-default", data: {dismiss: "modal"} %>
  </div>

<% end %>

app/views/jobs/_job.html.erb
<tr id="<%= job.id %>">
   <td><%= job.title %></td>
   <td><%= job.description %></td>
   <td>
       <%= link_to "Edit", edit_job_path(job), data: { toggle: "modal", target: "#myModal" } , class: "btn btn-primary btn-xs" %>
   </td>
   <td><%= link_to job, remote: true, method: :delete  do %>
            <button class="btn btn-danger btn-xs delete">Delete!</button>
        <% end %>

        <script>
          $('.delete').on('click', function(){
               $(this).closest("tr").remove();
               $('#index-flash-content').remove();
               $('.index-notice').remove();
               $('#index-flash').append($("<div id='index-notice'/>").addClass("col-md-12 column alert alert-success index-notice").text("Job was successfully removed!"));

          });
        </script>
   </td>
</tr>

app/views/jobs/destroy.js.erb
$('#jobs').html("<%= escape_javascript(render @jobs) %>");

app/views/jobs/index.html.erb
<div class="container">
  <div class="row clearfix" id="index-flash">
        <div class="col-md-12 column"  id="index-flash-content">
             <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
              <% end %>
        </div>
      </div>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1>
          Jobs Listing <small>Find yours!</small>
        </h1>
      </div>
      <div class="row clearfix">
        <div class="col-md-6 column">
        </div>
        <div class="col-md-6 column">
          <%= link_to new_job_path do %>
            <button type="button" class="btn btn-info btn-default">Add</button>
           <% end %>
        </div>
      </div>

      <% if @jobs.length > 0%>
          <div class="row clearfix">
            <div class="col-md-12 column">
              <table class="table">
                <thead>
                  <tr>
                    <th>
                      Title
                    </th>
                    <th>
                      Description
                    </th>
                    <th colspan="2">
                      Action
                    </th>
                  </tr>
                </thead>
                <tbody class="job-index">
                    <%= render @jobs %>
                </tbody>
              </table>
            </div>
          </div>

          <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                      <div id="job-modal"></div>
                    </div>
                </div>
          </div>

      <% end %>

    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>.: JobBoard :.</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>